### ISSUE TITLE
Investigate tests failures

### ISSUE THREAD

**Issue by hurricup** [Camelcade/TAP-Formatter-Camelcade#3]
Probably we have problem with windows path and some Test settings. 

See
-  http://www.cpantesters.org/distro/T/TAP-Formatter-Camelcade.html
- http://matrix.cpantesters.org/?dist=TAP-Formatter-Camelcade
- https://rt.cpan.org/Public/Bug/Display.html?id=128826

~~Also, add links above to the README~~

**Comment by hurricup** [comment]
Still problem on the CentOs

**Comment by eserte** [comment]
Still fails on CentOS 6+7.

**Comment by hurricup** [comment]
Passes on my CentOS 7 docker container. And CentOs 6 container is too tricky for plugin yet. So, can't test. Still 3 failures, acceptable for now. Will fix later if get some user feedback.
